# Example service, copy-paste to create new servicees.
# Don't forget to change the service name!

service: ${file(../../package.json):name}-service-a

custom:
  parcel:
    bundleNodeModules: true
  environment:
    default_env: &default_env
    SERVICE: ${self:service}
    dev:
      <<: *default_env
      STAGE: dev
    prod:
      <<: *default_env
      STAGE: prod

plugins:
  - serverless-plugin-parcel

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  memory: 512
  logRetentionInDays: 30
  environment: ${self:custom.environment.${self:provider.stage}}

functions:
  service-a-endpoint:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
