# Example service, copy-paste to create new servicees.
# Don't forget to change the service name!

service: ${file(../../package.json):name}-example-apig

custom:
  environment:
    default_env: &default_env
      SERVICE: ${self:service}
    dev:
      <<: *default_env
      STAGE: dev
    prod:
      <<: *default_env
      STAGE: prod

  output:
    handler: ../../scripts/stackOutput.handler

  prune:
    automatic: true
    number: 3

  parcel:
    bundleNodeModules: true

plugins:
  - serverless-plugin-parcel
  - serverless-prune-plugin
  - "@anttiviljami/serverless-stack-output"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  memory: 512
  logRetentionInDays: 30
  environment: ${self:custom.environment.${self:provider.stage}}

functions:
  healthcheck:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
